name: Build

on:
    push:
        branches:
            - main

jobs:
    build:
        name: testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setting node
              uses: actions/setup-node@v3
              with:
                node-version: '16'
                cache: npm
            - name: Installation
              run: npm install
            - name: Build
              run: npm run build